config/routes.rb
Rails.application.routes.draw do
  get 'affiliate_service/appointment_book'
  patch 'atualizar-agenda/(:appointbook_peopleassoci_id)' => 'affiliate_service#update_appointbook_peopleassoci', as: :update_appointbook_peopleassoci

  resources :bills_pays, path: "contas-a-pagar"
  resources :customer_configurations, path: "configuracoes"
  resources :payment_forms, path: "formas-pagamento"
  resources :financial_accounts, path: "contas-contabeis"
  resources :bills_receives, path: "contas-a-receber"
  resources :bank_accounts, path: "bancos"
  resources :categories, path: "plano-contas"
  # resources :subcategories, path: "subcategorias"
  resources :efforts, path: 'autorizacao-empenho'
  resources :type_incorporations, path: 'tipo-de-incorporacoes'
  resources :suppliers, path: 'fornecedores'
  resources :rooms, path: 'salas'
  resources :heritage_groups, path: 'grupo-do-patrimonio'
  # resources :financials, path: 'financas'

  # resources :monthly_payments, path: 'mensalidades' do
  #   match :pay, path: 'pagar',  via: [:get, :patch]
  # end

  resources :workplaces, path: 'locais-de-trabalho'
  resources :segments, path: 'segmentos'
  resources :occupations, path: 'funcoes'
  resources :offices, path: 'cargos'
  resources :patrimonies, path: 'patrimonios'
  resources :departments, path: 'departamentos'
  resources :roles, path: 'regras-de-acesso'
  
  devise_for :users, path: 'usuarios-do-sistema'
  resources :users, path: 'usuários-do-sistema' do
    collection do
      get 'meu-perfil' => 'users#edit_profile'
      post 'meu-perfil' => 'users#update_profile'
    end
  end


  resources :professionals, path: "profissionais"  do 
    resources :appointment_books, path: "agenda" do
      get 'confirma'
      get 'compareceu'
      get 'cancela'
      get 'iniciar-atendimento'
      get 'finalizar-atendimento'
      post 'agendar-retorno'
    end
  end
  
   resources :inventories, path: "estoque" do 
    resources :inventory_movements, path: "movimento-estoque"
   end
   
   resources :companies, path: "empresas-conveniadas"
   
   resources :member_access, path: "area-associado" do 
      collection do
        get 'meu-perfil' => 'member_access#edit_profile'
        post 'meu-perfil' => 'member_access#update_profile'
      end
   end
   
   devise_for :people_associateds, path: 'acesso-associado', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'people_associateds/sessions',
     passwords: 'people_associateds/passwords',
   }   
  
   resources :member_access_dependent, path: "area-dependente" do 
      collection do
        get 'meu-perfil' => 'member_access_dependent#edit_profile'
        post 'meu-perfil' => 'member_access_dependent#update_profile'
      end
   end

   devise_for :dependents, path: 'acesso-dependente', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'dependents/sessions',
     passwords: 'dependents/passwords',
   }

   resources :people_associateds, path: "associados" do
   	resources :dependents, path: "dependentes"
    collection do
      get 'autocomplete'
      get 'search'
      get 'print'
      get 'find_by_cpf'
      get 'load_all'
      get 'my_dependents'
    end  
   end
	
  get 'exportar-associados-em-xls' => 'people_associateds#people_associateds_to_xls', as: :people_associateds_to_xls
  get 'carteirinha/:id' => 'people_associateds#wallet', as: :wallet
  get 'ficha/:id' => 'people_associateds#record', as: :record
  get 'declaracao-uniao-estavel/(:id)' => 'people_associateds#stable_union_statement', as: :stable_union_statement
  get 'declaracao-associado/(:id)' => 'people_associateds#affiliate_statement', as: :affiliate_statement
  get 'desfiliacao-associado/(:id)' => 'people_associateds#affiliate_defiliation', as: :affiliate_defiliation
  get 'declaracao-comprovacao-de-dependente/(:id)' => 'people_associateds#declaration_of_dependency', as: :declaration_of_dependency
  get 'requerimento-desfiliacao/(:id)' => 'people_associateds#affiliation_requirement', as: :affiliation_requirement
  get 'desmarcar-associados-em-analise' => 'people_associateds#clear_all_in_analysis', as: :clear_all_in_analysis

  controller :reports do
    get :birthdays, path: "relatorio-aniversariantes"
    get :birthdays_print, path: "imprimir-relatorio-aniversariantes", as: :birthdays_print
    get :birthdays_to_xls, path: "exportar-relatorio-aniversariantes", as: :birthdays_to_xls
    get :associateds, path: "relatorio-associados"
    get :associateds_print, path: "relatorio-associados-impressao"
    get :associateds_xml, path: 'exportar-associados-em' 
    get :business, path: "relatorio-empresas"
    get :stocks, path: "relatorio-inventarios"
    get :heritages, path: "relatorio-patrimonios"
    get :calls, path: "relatorio-atendimentos"
    get :dependents, path: "relatorio-dependentes"
    get :print_dependents, path: "imprimir-relatorio-dependentes", as: :print_dependents
    get :monthly_payments, path: "relatorio-mensalidades", as: :monthly_payments_report
    get :voters, path: "relatorio-votantes"
    get :voters_print, path: "imprimir-relatorio-votantes", as: :voters_print
    get :voters_to_xls, path: "exportar-relatorio-votantes", as: :voters_to_xls
    get :bills_receives, path: "relatorio-contas-receber", as: :report_bills_receives
    get :bills_receives_print, path: "imprimir-relatorio-contas-receber", as: :bills_receives_print
    get :bills_receives_to_xls, path: "exportar-relatorio-contas-receber", as: :bills_receives_to_xls
    get :bills_pays, path: "relatorio-contas-pagar", as: :report_bills_pays
    get :bills_pays_print, path: "imprimir-relatorio-contas-pagar", as: :bills_pays_print
    get :bills_pays_to_xls, path: "exportar-relatorio-contas-pagar", as: :bills_pays_to_xls
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard
  
  ##### WHATSAPP
  # post 'twilio' => 'dashboard#twilio', as: :twilio
	# post 'twilio_message' => 'dashboard#twilio_message', as: :twilio_message
  ##### SMS
  # post '/twilio/sms'
  #get '/sms/confirma/:token' => 'twilio#confirma', as: :sms_confirma
  post 'comtele/sms'

  match 'site/filiacao' => 'site#inscription',  via: [:get, :post], as: :site_inscription
  match 'site/bem-vindos' => 'site#welcome',  via: [:get], as: :site_welcome
  
	root :to => "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dependents/confirmations_controller.rb
class Dependents::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/dependents/omniauth_callbacks_controller.rb
class Dependents::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/dependents/passwords_controller.rb
class Dependents::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/dependents/registrations_controller.rb
class Dependents::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/dependents/sessions_controller.rb
class Dependents::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create    
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/dependents/unlocks_controller.rb
class Dependents::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize, if: :user_signed_in?
  before_action :set_people_associated
  before_action :set_dependent, only: [:show, :edit, :update, :destroy]
  
  # GET /dependents
  # GET /dependents.json
  def index
    #@dependents = @people_associated.dependents
    filterrific
  end

  # GET /dependents/1
  # GET /dependents/1.json
  def show
  end

  # GET /dependents/new
  def new
    @dependent = @people_associated.dependents.new
  end

  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents
  # POST /dependents.json
  def create
    @dependent = @people_associated.dependents.new(dependent_params)
    filterrific
    @saved = @dependent.save

    respond_to do |format|
      if @saved
        format.html { redirect_to @dependent, notice: "#{Dependent.model_name.human} #{I18n.t('default_messages.created')}" }
        format.json { render :show, status: :created, location: @dependent }
        format.js
      else
        format.html { render :new }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /dependents/1
  # PATCH/PUT /dependents/1.json
  def update

    if params[:dependent][:password].blank?
      params[:dependent].delete("password")
      params[:dependent].delete("password_confirmation")
    end

    respond_to do |format|
      filterrific

      @saved = @dependent.update(dependent_params)      

      if @saved  
        format.html { redirect_to @dependent, notice: "#{Dependent.model_name.human} #{I18n.t('default_messages.updated')}" }
        format.json { render :show, status: :ok, location: @people_associated }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /dependents/1
  # DELETE /dependents/1.json
  def destroy
    @dependent.destroy
    filterrific

    respond_to do |format|
      format.html { redirect_to dependents_url, notice: "#{Dependent.model_name.human} #{I18n.t('default_messages.destroyed')}" }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_people_associated
      @people_associated = PeopleAssociated.find(params[:people_associated_id])
    end

    def set_dependent
      @dependent = @people_associated.dependents.find(params[:id])
    end

    def filterrific
      @filterrific = initialize_filterrific(
          Dependent.joins(:people_associated),
          params[:filterrific],
          default_filter_params: { sorted_by: 'created_at_desc', with_people_associated_id: @people_associated.id },
          persistence_id: false
        ) or return
        
      @dependents = @filterrific.find.page(params[:page])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dependent_params
      params.require(:dependent).permit(:is_student, :phone, :cell_phone, :username, :password, :password_confirmation, :people_associated_id, :name, :birthdate, :degree_of_kinship, :other_manual, :benefit_until, :validate_statement, :with_special_needs, :active, system_attachments_attributes: [:id, :name, :archive, :_destroy])
    end
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/views/dependents/_form.html.erb
<div class="card">
  <div id="card_header_dependent" class="card-header ch-alt m-b-20"></div>

  <div class="card-body card-padding">
    <%= simple_form_for([@people_associated, @dependent], html: { class: "", role: "form" }, remote: true) do |f| %>
    <div id="people_associated_dependent_error"></div>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group fg-line">     
          <%= f.input :people_associated_id, as: :hidden, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group fg-line">     
          <%= f.label :name, class: "fg-label" %>                   
          <%= f.input :name, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col-sm-4">
        <div class="form-group fg-line">
          <%= f.label :birthdate, class: "fg-label m-b-1" %>
          <%= f.input :birthdate, as: :string, input_html: {class: "form-control mask-date", value: f.object.birthdate ? I18n.l(f.object.birthdate) : ''}, label: false  %>  


        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group fg-line">
          <%= f.label :benefit_until, class: "fg-label m-b-1" %>
          <%= f.input :benefit_until, as: :string, input_html: {class: "form-control mask-date", value: f.object.benefit_until ? I18n.l(f.object.benefit_until) : ''}, label: false  %>  
        </div>
      </div>


      <div class="col-sm-4">
        <div class="form-group fg-line">     
          <%= f.label :degree_of_kinship, class: "fg-label" %>                   
          <%= f.input :degree_of_kinship, collection: Dependent::DEGREE_OF_KINSHIP, input_html: {class: "selectpicker", "data-live-search": true, "data-name": "other_manual_#{@dependent.id}"}, label: false %>
        </div>
      </div>

      
      <div id="other_manual_<%=@dependent.id%>" class="form-group" style="display:<%= @dependent.degree_of_kinship_other? ? 'block' : 'none' %>;"> 
        <div class="col-sm-2">
          <div class="fg-line">    
            <%= f.label :other_manual, class: "fg-label" %> 
            <%= f.input :other_manual, input_html: {class: "form-control"}, label: false %>
          </div>
        </div>
      </div>


      <div class="col-sm-3">
        <div class="form-group fg-line">
            <%= f.label :phone, class: "fg-label" %>
            <%= f.input :phone, input_html: {class: "input-sm form-control fg-input mask-phone-fixo", "data-mask": "(00) 0000-0000"}, label: false %>                        
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group fg-line">
            <%= f.label :cell_phone, class: "fg-label" %>
            <%= f.input :cell_phone, input_html: {class: "input-sm form-control fg-input mask-phone", "data-mask": "(00) 0000-0000"}, label: false %>                        
        </div>
      </div>

      <div class="col-sm-4">
          <div class="cpf form-group fg-line">
              <%= f.label :cpf, class: "fg-label" %>
              <%= f.input :cpf, input_html: {class: 'input-sm form-control fg-input input-mask mask-cpf', "data-mask": "000.000.000-00" , "data-id": @dependent.id }, label: false %>   
          </div>
      </div>

      <div class="col-sm-4">
          <div class="form-group fg-line ">
              <%= f.label :rg, class: "fg-label" %>
              <%= f.input :rg, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
          </div>
      </div>

      <div class="col-sm-4">
          <div class="form-group fg-line ">
              <%= f.label :dispatcher_organ, class: "fg-label" %>
              <%= f.input :dispatcher_organ, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
          </div>
      </div>
    </div>


    <div class="row">
      <div class="col-sm-6">
        <div class="form-group"> 
          <div class="fg-line">    
            <%= f.label :validate_statement, class: "fg-label" %> 
            <%= f.input :validate_statement, input_html: {class: "form-control"}, label: false %>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="checkbox m-b-15">
          <label>
            <%= f.check_box :with_special_needs %>
            <i class="input-helper"></i> 
            <%= Dependent.human_attribute_name :with_special_needs %>                            
          </label>
        </div>        
      </div>

      <div class="col-sm-6">
        <div class="checkbox m-b-15">
          <label>
            <%= f.check_box :is_student %>
            <i class="input-helper"></i> 
            <%= Dependent.human_attribute_name :is_student %>                            
          </label>
        </div>        
      </div>   

      <div class="col-sm-6">
        <div class="checkbox m-b-15">
          <label>
            <%= f.check_box :active %>
            <i class="input-helper"></i> 
            <%= Dependent.human_attribute_name :active %>                            
          </label>
        </div>        
      </div>   


      <div class="card-header">
        <h2><i class="zmdi zmdi-collection-text"></i> Dados de acesso</h2>
      </div>


      <div class="card-body card-padding">
          <div class="row">
              <div class="col-sm-4">
                  <div class="form-group fg-line">     
                      <%= f.label :username, class: "fg-label" %>                   
                      <%= f.input :username, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
                  </div>
              </div>

              <div class="col-sm-4">
                  <div class="form-group fg-line">     
                      <%= f.label :password, class: "fg-label" %>                   
                      <%= f.input :password, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
                  </div>
              </div>

              <div class="col-sm-4">
                  <div class="form-group fg-line">     
                      <%= f.label :password_confirmation, class: "fg-label" %>                   
                      <%= f.input :password_confirmation, input_html: {class: "input-sm form-control fg-input"}, label: false  %>
                  </div>
              </div>
          </div>
        </div>       
    </div>


    <%= f.button :submit, onclick: "showPreLoader()", class: "btn bgm-green waves-effect" %>     

    <%= link_to people_associated_dependents_path, remote: true, onclick: "showPreLoader()", "data-toggle": "tooltip", "data-placement":"bottom", "title": "Voltar", class: 'btn btn-primary waves-effect' do %>
    <i class="zmdi zmdi-arrow-back"></i>
    <% end %>

    <% end %>    
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    loadSelectPicker();
    
    $(".mask-phone").mask("(99) 9 9999-9999");
    $(".mask-phone-fixo").mask("(99) 9999-9999");
    $(".mask-cpf").mask("999.999.999-99");

    $('#dependent_degree_of_kinship').change(function(){
      var key = $(this).attr('data-name');
      if( parseInt($(this).val()) == 12 ) {
        $("#"+key).show();        
      } else {
        $("#"+key).hide();
        $("#dependent_other_manual").val("");
      }

    });
  });
</script>

app/views/dependents/_index.html.erb
<div class="custom-form">
  <%= form_for_filterrific @filterrific, url: people_associated_dependents_url(@people_associated), html: { class: "", role: "form" }, remote: true do |f| %>

  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-4">
      <div class="form-group fg-line">   
        <%= f.hidden_field(:with_people_associated_id, value: @people_associated.id ) %>
      </div>
    </div>
    <% if false %>
    <div class="col-md-4 col-sm-4 col-xs-4">
      <div class="form-group fg-line">     
        <%= f.label Dependent.human_attribute_name(:name), class: "fg-label" %>   
        <%= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control clearable') %>
      </div>
    </div>


    <div class="col-md-2 col-sm-2 col-xs-2">
      <div class="form-group fg-line">  
        <%= f.submit 'Filtrar', class: "btn bgm-green waves-effect" %>                
        <%= link_to('Resetar Filtros', reset_filterrific_url, class: "btn bgm-red waves-effect", remote: true) if false%>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="input-group">
      <%= f.text_field(:search_query, class: 'filterrific-periodically-observed form-control clearable', placeholder: "Buscar dependentes de #{@people_associated.name}") %>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default" onClick=""><i class="fa fa-search"></i></button>
      </span>
    </div>
  </div>
  <%= render_filterrific_spinner %>      
  <% end %>
</div>

<div class="card">
  <div class="card-header ch-alt m-b-20">                                    
    <%= link_to new_people_associated_dependent_path(@people_associated), remote: true, onclick: "showPreLoader();", class: 'btn bgm-green btn-float waves-effect' do %>
    <i class="zmdi zmdi-plus"></i>
    <% end %>

    <h2><i class="zmdi zmdi-account-box-o"></i> <%= Dependent.model_name.human.pluralize %> - <%= @people_associated.name %></h2>
  </div>

  <div class="card-body"> 
    <div class="table-responsive">
      <%= render( partial: 'dependents/list', locals: { dependents: @dependents } ) %>
    </div>                       
  </div>
</div>
<script>

  function submitFormFilter() {
    $("#filterrific_filter").submit():
  }
  $(document).ready(function() {    
    var form = $("#filterrific_filter");
    var input = $("#filterrific_search_query");
    //var f = $("");

    input.change()

  })
  jQuery(function($) {
    // /////
    // CLEARABLE INPUT
    function tog(v){return v?'addClass':'removeClass';} 
    $(document).on('input', '.clearable', function(){
      $(this)[tog(this.value)]('x');
    }).on('mousemove', '.x', function( e ){
      $(this)[tog(this.offsetWidth-18 < e.clientX-this.getBoundingClientRect().left)]('onX');   
    }).on('touchstart click', '.onX', function( ev ){
      ev.preventDefault();
      $(this).removeClass('x onX').val('').change();
    });


  });
</script>

app/views/dependents/_list.html.erb
<div id="filterrific_results">
	<table class="table table-striped table-bordered table-hover">
		<thead>
		  <tr>
		    <th><%= Dependent.human_attribute_name(:name) %></th>
		    <th><%= Dependent.human_attribute_name(:birthdate) %></th>
		    <th><%= Dependent.human_attribute_name(:degree_of_kinship) %></th>
		    <th><%= Dependent.human_attribute_name(:active) %></th>
		    <th><%= Dependent.human_attribute_name(:with_special_needs) %></th>
		    <th><%= Dependent.human_attribute_name(:validate_statement) %></th>
		    <th></th>         
		  </tr>
		</thead>

		<tbody>
		  <%= content_tag_for(:tr, @dependents) do |dependent| %>
		    <td><%= dependent.name %></td>
		    <td><%=I18n.l dependent.birthdate if dependent.birthdate.present? %></td>
		    <td><%= dependent.degree_of_kinship_name %></td>
		    <td><%= dependent.active ? "Sim" : "Não"  %></td>
		    <td><%= dependent.with_special_needs ? "Sim" : "Não"  %></td>
		    <td><%= dependent.validate_statement %></td>
		    <td>
		      <%= link_to edit_people_associated_dependent_path(@people_associated, dependent), class: "btn btn-info waves-effect", remote: true, onclick: "showPreLoader();" do %>
		        <%= content_tag(:i, nil, class: "zmdi zmdi-edit") %>
		      <% end %>

		      <%= link_to people_associated_dependent_path(@people_associated, dependent), method: :delete, data: { confirm:  I18n.t('default_messages.confirm')  }, remote: true, class: "btn btn-danger waves-effect" do %>
		        <%= content_tag(:i, nil, class: "zmdi zmdi-delete") %>
		      <% end %>
		    </td>  
		  <% end %>
		</tbody>
	</table>

	<%= will_paginate @dependents, renderer: BootstrapPagination::Rails %>
</div>

app/views/dependents/edit.html.erb
<div class="page-header">
  <%= link_to dependents_path, class: 'btn btn-default waves-effect' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @dependent, class: 'btn btn-primary waves-effect' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing dependent</h1>
</div>

<%= render 'form' %>

app/views/dependents/new.html.erb
<div class="page-header">
  <%= link_to dependents_path, class: 'btn btn-default waves-effect' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New dependent</h1>
</div>

<%= render 'form' %>

app/views/dependents/show.html.erb
<div class="page-header">
  <%= link_to dependents_path, class: 'btn btn-default waves-effect' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_dependent_path(@dependent), class: 'btn btn-primary waves-effect' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show dependent</h1>
</div>

<dl class="dl-horizontal">
  <dt>People associateds:</dt>
  <dd><%= @dependent.people_associateds %></dd>

  <dt>Name:</dt>
  <dd><%= @dependent.name %></dd>

  <dt>Birthdate:</dt>
  <dd><%= @dependent.birthdate %></dd>

  <dt>Degree of kinship:</dt>
  <dd><%= @dependent.degree_of_kinship %></dd>

</dl>