config/routes.rb
Rails.application.routes.draw do
  get 'affiliate_service/appointment_book'
  patch 'atualizar-agenda/(:appointbook_peopleassoci_id)' => 'affiliate_service#update_appointbook_peopleassoci', as: :update_appointbook_peopleassoci

  resources :bills_pays, path: "contas-a-pagar"
  resources :customer_configurations, path: "configuracoes"
  resources :payment_forms, path: "formas-pagamento"
  resources :financial_accounts, path: "contas-contabeis"
  resources :bills_receives, path: "contas-a-receber"
  resources :bank_accounts, path: "bancos"
  resources :categories, path: "plano-contas"
  # resources :subcategories, path: "subcategorias"
  resources :efforts, path: 'autorizacao-empenho'
  resources :type_incorporations, path: 'tipo-de-incorporacoes'
  resources :suppliers, path: 'fornecedores'
  resources :rooms, path: 'salas'
  resources :heritage_groups, path: 'grupo-do-patrimonio'
  # resources :financials, path: 'financas'

  # resources :monthly_payments, path: 'mensalidades' do
  #   match :pay, path: 'pagar',  via: [:get, :patch]
  # end

  resources :workplaces, path: 'locais-de-trabalho'
  resources :segments, path: 'segmentos'
  resources :occupations, path: 'funcoes'
  resources :offices, path: 'cargos'
  resources :patrimonies, path: 'patrimonios'
  resources :departments, path: 'departamentos'
  resources :roles, path: 'regras-de-acesso'
  
  devise_for :users, path: 'usuarios-do-sistema'
  resources :users, path: 'usuários-do-sistema' do
    collection do
      get 'meu-perfil' => 'users#edit_profile'
      post 'meu-perfil' => 'users#update_profile'
    end
  end


  resources :professionals, path: "profissionais"  do 
    resources :appointment_books, path: "agenda" do
      get 'confirma'
      get 'compareceu'
      get 'cancela'
      get 'iniciar-atendimento'
      get 'finalizar-atendimento'
      post 'agendar-retorno'
    end
  end
  
   resources :inventories, path: "estoque" do 
    resources :inventory_movements, path: "movimento-estoque"
   end
   
   resources :companies, path: "empresas-conveniadas"
   
   resources :member_access, path: "area-associado" do 
      collection do
        get 'meu-perfil' => 'member_access#edit_profile'
        post 'meu-perfil' => 'member_access#update_profile'
      end
   end
   
   devise_for :people_associateds, path: 'acesso-associado', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'people_associateds/sessions',
     passwords: 'people_associateds/passwords',
   }   
  
   resources :member_access_dependent, path: "area-dependente" do 
      collection do
        get 'meu-perfil' => 'member_access_dependent#edit_profile'
        post 'meu-perfil' => 'member_access_dependent#update_profile'
      end
   end

   devise_for :dependents, path: 'acesso-dependente', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'dependents/sessions',
     passwords: 'dependents/passwords',
   }

   resources :people_associateds, path: "associados" do
   	resources :dependents, path: "dependentes"
    collection do
      get 'autocomplete'
      get 'search'
      get 'print'
      get 'find_by_cpf'
      get 'load_all'
      get 'my_dependents'
    end  
   end
	
  get 'exportar-associados-em-xls' => 'people_associateds#people_associateds_to_xls', as: :people_associateds_to_xls
  get 'carteirinha/:id' => 'people_associateds#wallet', as: :wallet
  get 'ficha/:id' => 'people_associateds#record', as: :record
  get 'declaracao-uniao-estavel/(:id)' => 'people_associateds#stable_union_statement', as: :stable_union_statement
  get 'declaracao-associado/(:id)' => 'people_associateds#affiliate_statement', as: :affiliate_statement
  get 'desfiliacao-associado/(:id)' => 'people_associateds#affiliate_defiliation', as: :affiliate_defiliation
  get 'declaracao-comprovacao-de-dependente/(:id)' => 'people_associateds#declaration_of_dependency', as: :declaration_of_dependency
  get 'requerimento-desfiliacao/(:id)' => 'people_associateds#affiliation_requirement', as: :affiliation_requirement
  get 'desmarcar-associados-em-analise' => 'people_associateds#clear_all_in_analysis', as: :clear_all_in_analysis

  controller :reports do
    get :birthdays, path: "relatorio-aniversariantes"
    get :birthdays_print, path: "imprimir-relatorio-aniversariantes", as: :birthdays_print
    get :birthdays_to_xls, path: "exportar-relatorio-aniversariantes", as: :birthdays_to_xls
    get :associateds, path: "relatorio-associados"
    get :associateds_print, path: "relatorio-associados-impressao"
    get :associateds_xml, path: 'exportar-associados-em' 
    get :business, path: "relatorio-empresas"
    get :stocks, path: "relatorio-inventarios"
    get :heritages, path: "relatorio-patrimonios"
    get :calls, path: "relatorio-atendimentos"
    get :dependents, path: "relatorio-dependentes"
    get :print_dependents, path: "imprimir-relatorio-dependentes", as: :print_dependents
    get :monthly_payments, path: "relatorio-mensalidades", as: :monthly_payments_report
    get :voters, path: "relatorio-votantes"
    get :voters_print, path: "imprimir-relatorio-votantes", as: :voters_print
    get :voters_to_xls, path: "exportar-relatorio-votantes", as: :voters_to_xls
    get :bills_receives, path: "relatorio-contas-receber", as: :report_bills_receives
    get :bills_receives_print, path: "imprimir-relatorio-contas-receber", as: :bills_receives_print
    get :bills_receives_to_xls, path: "exportar-relatorio-contas-receber", as: :bills_receives_to_xls
    get :bills_pays, path: "relatorio-contas-pagar", as: :report_bills_pays
    get :bills_pays_print, path: "imprimir-relatorio-contas-pagar", as: :bills_pays_print
    get :bills_pays_to_xls, path: "exportar-relatorio-contas-pagar", as: :bills_pays_to_xls
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard
  
  ##### WHATSAPP
  # post 'twilio' => 'dashboard#twilio', as: :twilio
	# post 'twilio_message' => 'dashboard#twilio_message', as: :twilio_message
  ##### SMS
  # post '/twilio/sms'
  #get '/sms/confirma/:token' => 'twilio#confirma', as: :sms_confirma
  post 'comtele/sms'

  match 'site/filiacao' => 'site#inscription',  via: [:get, :post], as: :site_inscription
  match 'site/bem-vindos' => 'site#welcome',  via: [:get], as: :site_welcome
  
	root :to => "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/office.rb
class Office < ApplicationRecord
	validates :name, presence: true
	has_many :people_associateds

	default_scope  { order(:name => :asc) }
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize, if: :user_signed_in?
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.paginate(page: params[:page])
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)
    @saved = @office.save

    respond_to do |format|
      if @saved
        @url =  params[:create_and_add] ? new_office_url : offices_url  
        format.html { redirect_to @url, notice: "#{Office.model_name.human} #{I18n.t('default_messages.created')}" }
        format.json { render :show, status: :created, location: @office }
        format.js
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to offices_url, notice: "#{Office.model_name.human} #{I18n.t('default_messages.updated')}" }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: "#{Office.model_name.human} #{I18n.t('default_messages.destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<div class="card">  
    <%= simple_form_for(@office, html: { class: "form-horizontal", role: "form" }) do |f| %>
      <%= f.error_notification %>
      <div class="card-header">
        <h2><i class="fa fa-cube"></i> Dados <%= Office.model_name.human %></h2>
      </div>

      <div class="card-body card-padding">
        <div class="row">
          
          <div class="col-sm-4">    
            <div class="fg-line ">
              <%= f.label :name, class: "fg-label" %>
              <%= f.input :name, input_html: {class: "input-sm form-control fg-input"}, label: false %>
            </div>
          </div>
        </div>
      </div>
      
      <div class="card-body card-padding">
        <%= submit_tag 'Criar e adicionar', class: "btn bgm-teal waves-effect", name: 'create_and_add' if !edit_mode? %>
        <%= f.button :submit, class: "btn bgm-green waves-effect" %>
        <%= link_to "Cancelar", offices_path, class: "btn bgm-red waves-effect" %>
      </div>  
      <% end %>    
    </div>

app/views/offices/_modal_office.html.erb
<div class="modal fade" id="modal_new_office" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div id="card_header_office"></div>     
      </div>

      <div class="modal-body">
       <%= preloader %>
       <div id="office_content">
       </div>
     </div>
   </div>
 </div>
</div>

app/views/offices/_remote_form.html.erb
<%= simple_form_for(@office, html: { class: "form-horizontal", role: "form" }, remote: true) do |f| %>
<%= f.error_notification %>
<div id='office_error'></div>
<div class="card-body">
  <div class="row">

    <div class="col-sm-12">    
      <div class="fg-line ">
        <%= f.label :name, class: "fg-label" %>
        <%= f.input :name, input_html: {class: "input-sm form-control fg-input"}, label: false %>
      </div>
    </div>
  </div>
</div>

<div class="modal-footer">
  <%= f.button :submit, onclick: "showPreLoader()", class: "btn bgm-green waves-effect" %>     
  <button type="button" class="btn btn-link" data-dismiss="modal">Cancelar</button>
</div>  
<% end %>

app/views/offices/create.js.erb
<% if @saved %>
	$('#people_associated_office_id').append($('<option>', {
	    value: "<%=@office.id%>",
	    text: "<%=@office.name%>"
	}));

	$('.selectpicker').selectpicker('refresh');
	$('#modal_new_office').modal('hide');
<% else %>	
	$("#occupation_error").html("<%= escape_javascript errors(@office) %>")
<% end %>	

hiddenPreLoader(); 

app/views/offices/edit.html.erb
<div class="card">
	<div class="card-header ch-alt m-b-20">  
		<%= link_to offices_path, "data-toggle": "tooltip", "data-placement":"bottom", "title": "Voltar", class: 'btn bgm-deeporange btn-float waves-effect' do %>
		<i class="zmdi zmdi-arrow-left"></i>
		<% end  if false%>

		<%= link_to @office, class: 'btn btn-primary waves-effect' do %>
		    <span class="glyphicon glyphicon-info-sign"></span>
		    Show
		<% end if false%>

		<h2><i class="fa fa-cubes"></i> <%= "Editando cargo" %></h2>
	</div>

	<%= render 'form' %>
</div>

app/views/offices/index.html.erb
<div class="card">
<div class="card-header ch-alt m-b-20">                                    
  <%= link_to new_office_path, class: 'btn bgm-green btn-float waves-effect' do %>
  <i class="zmdi zmdi-plus"></i>
  <% end %>

  <h2><i class="fa fa-cubes"></i> <%= Office.model_name.human.pluralize %></h2>
</div>

<div class="card-body card-padding">       
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th></th>       
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @offices) do |office| %>
        <td><%= office.name %></td>           
        <td style="width: 200px;">
          <%= link_to office, class: "btn bgm-orange waves-effect" do %>
            <%= content_tag(:i, nil, class: "zmdi zmdi-eye") %>
          <% end %>
          
          <%= link_to edit_office_path(office), class: "btn btn-info waves-effect" do %>
            <%= content_tag(:i, nil, class: "zmdi zmdi-edit") %>
          <% end %>

          <%= link_to office, method: :delete, data: { confirm: I18n.t('default_messages.confirm')  } , class: "btn btn-danger waves-effect" do %>
            <%= content_tag(:i, nil, class: "zmdi zmdi-delete") %>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= will_paginate @offices, renderer: BootstrapPagination::Rails %>                               
  </div>
</div>

app/views/offices/new.html.erb
<div class="card">
	<div class="card-header ch-alt">  
		<%= link_to offices_path, "data-toggle": "tooltip", "data-placement":"bottom", "title": "Voltar", class: 'btn bgm-deeporange btn-float waves-effect' do %>
		<i class="zmdi zmdi-arrow-left"></i>
		<% end  if false%>
		<h2><i class="fa fa-cubes"></i> <%= "Novo cargo" %> <i class="c-gray"></i></h2>
	</div>

	<%= render 'form' %>
</div>

app/views/offices/new.js.erb
<% js = escape_javascript(
  render(partial: 'offices/remote_form')
) %>

$("#office_content").html("<%= js %>");
$("#card_header_office").html("<h2><i class='zmdi zmdi-account-box-o'></i> Novo <%= Office.model_name.human %></h2>")

hiddenPreLoader(); 

app/views/offices/show.html.erb
<div class="page-header">
  <%= link_to offices_path, class: 'btn btn-default waves-effect' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_office_path(@office), class: 'btn btn-primary waves-effect' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show office</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @office.name %></dd>

</dl>