config/routes.rb
Rails.application.routes.draw do
  get 'affiliate_service/appointment_book'
  patch 'atualizar-agenda/(:appointbook_peopleassoci_id)' => 'affiliate_service#update_appointbook_peopleassoci', as: :update_appointbook_peopleassoci

  resources :bills_pays, path: "contas-a-pagar"
  resources :customer_configurations, path: "configuracoes"
  resources :payment_forms, path: "formas-pagamento"
  resources :financial_accounts, path: "contas-contabeis"
  resources :bills_receives, path: "contas-a-receber"
  resources :bank_accounts, path: "bancos"
  resources :categories, path: "plano-contas"
  # resources :subcategories, path: "subcategorias"
  resources :efforts, path: 'autorizacao-empenho'
  resources :type_incorporations, path: 'tipo-de-incorporacoes'
  resources :suppliers, path: 'fornecedores'
  resources :rooms, path: 'salas'
  resources :heritage_groups, path: 'grupo-do-patrimonio'
  # resources :financials, path: 'financas'

  # resources :monthly_payments, path: 'mensalidades' do
  #   match :pay, path: 'pagar',  via: [:get, :patch]
  # end

  resources :workplaces, path: 'locais-de-trabalho'
  resources :segments, path: 'segmentos'
  resources :occupations, path: 'funcoes'
  resources :offices, path: 'cargos'
  resources :patrimonies, path: 'patrimonios'
  resources :departments, path: 'departamentos'
  resources :roles, path: 'regras-de-acesso'
  
  devise_for :users, path: 'usuarios-do-sistema'
  resources :users, path: 'usuários-do-sistema' do
    collection do
      get 'meu-perfil' => 'users#edit_profile'
      post 'meu-perfil' => 'users#update_profile'
    end
  end


  resources :professionals, path: "profissionais"  do 
    resources :appointment_books, path: "agenda" do
      get 'confirma'
      get 'compareceu'
      get 'cancela'
      get 'iniciar-atendimento'
      get 'finalizar-atendimento'
      post 'agendar-retorno'
    end
  end
  
   resources :inventories, path: "estoque" do 
    resources :inventory_movements, path: "movimento-estoque"
   end
   
   resources :companies, path: "empresas-conveniadas"
   
   resources :member_access, path: "area-associado" do 
      collection do
        get 'meu-perfil' => 'member_access#edit_profile'
        post 'meu-perfil' => 'member_access#update_profile'
      end
   end
   
   devise_for :people_associateds, path: 'acesso-associado', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'people_associateds/sessions',
     passwords: 'people_associateds/passwords',
   }   
  
   resources :member_access_dependent, path: "area-dependente" do 
      collection do
        get 'meu-perfil' => 'member_access_dependent#edit_profile'
        post 'meu-perfil' => 'member_access_dependent#update_profile'
      end
   end

   devise_for :dependents, path: 'acesso-dependente', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'dependents/sessions',
     passwords: 'dependents/passwords',
   }

   resources :people_associateds, path: "associados" do
   	resources :dependents, path: "dependentes"
    collection do
      get 'autocomplete'
      get 'search'
      get 'print'
      get 'find_by_cpf'
      get 'load_all'
      get 'my_dependents'
    end  
   end
	
  get 'exportar-associados-em-xls' => 'people_associateds#people_associateds_to_xls', as: :people_associateds_to_xls
  get 'carteirinha/:id' => 'people_associateds#wallet', as: :wallet
  get 'ficha/:id' => 'people_associateds#record', as: :record
  get 'declaracao-uniao-estavel/(:id)' => 'people_associateds#stable_union_statement', as: :stable_union_statement
  get 'declaracao-associado/(:id)' => 'people_associateds#affiliate_statement', as: :affiliate_statement
  get 'desfiliacao-associado/(:id)' => 'people_associateds#affiliate_defiliation', as: :affiliate_defiliation
  get 'declaracao-comprovacao-de-dependente/(:id)' => 'people_associateds#declaration_of_dependency', as: :declaration_of_dependency
  get 'requerimento-desfiliacao/(:id)' => 'people_associateds#affiliation_requirement', as: :affiliation_requirement
  get 'desmarcar-associados-em-analise' => 'people_associateds#clear_all_in_analysis', as: :clear_all_in_analysis

  controller :reports do
    get :birthdays, path: "relatorio-aniversariantes"
    get :birthdays_print, path: "imprimir-relatorio-aniversariantes", as: :birthdays_print
    get :birthdays_to_xls, path: "exportar-relatorio-aniversariantes", as: :birthdays_to_xls
    get :associateds, path: "relatorio-associados"
    get :associateds_print, path: "relatorio-associados-impressao"
    get :associateds_xml, path: 'exportar-associados-em' 
    get :business, path: "relatorio-empresas"
    get :stocks, path: "relatorio-inventarios"
    get :heritages, path: "relatorio-patrimonios"
    get :calls, path: "relatorio-atendimentos"
    get :dependents, path: "relatorio-dependentes"
    get :print_dependents, path: "imprimir-relatorio-dependentes", as: :print_dependents
    get :monthly_payments, path: "relatorio-mensalidades", as: :monthly_payments_report
    get :voters, path: "relatorio-votantes"
    get :voters_print, path: "imprimir-relatorio-votantes", as: :voters_print
    get :voters_to_xls, path: "exportar-relatorio-votantes", as: :voters_to_xls
    get :bills_receives, path: "relatorio-contas-receber", as: :report_bills_receives
    get :bills_receives_print, path: "imprimir-relatorio-contas-receber", as: :bills_receives_print
    get :bills_receives_to_xls, path: "exportar-relatorio-contas-receber", as: :bills_receives_to_xls
    get :bills_pays, path: "relatorio-contas-pagar", as: :report_bills_pays
    get :bills_pays_print, path: "imprimir-relatorio-contas-pagar", as: :bills_pays_print
    get :bills_pays_to_xls, path: "exportar-relatorio-contas-pagar", as: :bills_pays_to_xls
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard
  
  ##### WHATSAPP
  # post 'twilio' => 'dashboard#twilio', as: :twilio
	# post 'twilio_message' => 'dashboard#twilio_message', as: :twilio_message
  ##### SMS
  # post '/twilio/sms'
  #get '/sms/confirma/:token' => 'twilio#confirma', as: :sms_confirma
  post 'comtele/sms'

  match 'site/filiacao' => 'site#inscription',  via: [:get, :post], as: :site_inscription
  match 'site/bem-vindos' => 'site#welcome',  via: [:get], as: :site_welcome
  
	root :to => "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
  before_action :authorize, except: [:print_dependents, :associateds_print, :associateds_xml, :birthdays_print, :birthdays_to_xls], if: :user_signed_in?

  def bills_pays
    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["with_category_ids","reset_filterrific", 'with_due_date_gte', 'with_situation_flag', 'with_supplier_ids', "sorted_by", "grouped_by"]).to_h.stringify_keys
    else
      @filterrific_params = nil
    end

       @filterrific = initialize_filterrific(
          BillsPay
          .joins(:supplier, :category)
          .includes(:supplier, :category),
          @filterrific_params,
          select_options: {
            sorted_by: BillsPay.options_for_sorted_by
          },
          default_filter_params: { sorted_by: '' }
        ) or return

       
      @bills_pays = @filterrific.find.page(params[:page]) 

      if params[:filterrific].present? && !params[:filterrific][:grouped_by].blank?        
          if params[:filterrific][:grouped_by] === 'category_id'
            @grouped = @bills_pays.group_by(&:category_id)          
          elsif params[:filterrific][:grouped_by] === 'supplier_id'
            @grouped = @bills_pays.group_by(&:supplier_id)
          end
      else
          @grouped = @bills_pays.group_by(&:category_id)  
      end

      respond_to do |format|
        format.html
        format.js
      end
  end


  def bills_pays_print
    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["with_category_ids","reset_filterrific", 'with_due_date_gte', 'with_situation_flag', 'with_supplier_ids', "sorted_by", "grouped_by"]).to_h.stringify_keys
    else
      @filterrific_params = nil
    end

       @filterrific = initialize_filterrific(
          BillsPay
          .joins(:supplier, :category)
          .includes(:supplier, :category),
          @filterrific_params,
          select_options: {
            sorted_by: BillsPay.options_for_sorted_by
          },
          default_filter_params: { sorted_by: '' }
        ) or return

       
      @bills_pays = @filterrific.find.page(params[:page]) 

      if params[:filterrific].present? && !params[:filterrific][:grouped_by].blank?        
          if params[:filterrific][:grouped_by] === 'category_id'
            @grouped = @bills_pays.group_by(&:category_id)          
          elsif params[:filterrific][:grouped_by] === 'supplier_id'
            @grouped = @bills_pays.group_by(&:supplier_id)
          end
      else
          @grouped = @bills_pays.group_by(&:category_id)  
      end

      respond_to do |format|
        format.html { render layout: 'print' }
        format.js
      end
  end

  def bills_receives
    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["with_category_ids","reset_filterrific", 'with_due_date_gte', 'with_situation_flag', "sorted_by", "grouped_by"]).to_h.stringify_keys
    else
      @filterrific_params = nil
    end

       @filterrific = initialize_filterrific(
          BillsReceife
          .joins(:people_associated, :category, :financial_account)
          .includes(:people_associated, :category, :financial_account),
          @filterrific_params,
          select_options: {
            sorted_by: BillsReceife.options_for_sorted_by
          },
          default_filter_params: { sorted_by: '' }
        ) or return

       
      @bills_receives = @filterrific.find.page(params[:page]) 

      if params[:filterrific].present? && !params[:filterrific][:grouped_by].blank?        
          if params[:filterrific][:grouped_by] === 'category_id'
            @grouped = @bills_receives.group_by(&:category_id)          
          elsif params[:filterrific][:grouped_by] === 'financial_account_id'
            @grouped = @bills_receives.group_by(&:financial_account_id)
          end
      else
          @grouped = @bills_receives.group_by(&:category_id)  
      end

      respond_to do |format|
        format.html
        format.js
      end
  end

  def bills_receives_print

    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["with_category_ids","reset_filterrific", 'with_due_date_gte', 'with_situation_flag', "sorted_by", "grouped_by"]).to_h.stringify_keys
    else
      @filterrific_params = nil
    end

       @filterrific = initialize_filterrific(
          BillsReceife
          .joins(:people_associated, :category, :financial_account)
          .includes(:people_associated, :category, :financial_account),
          @filterrific_params,
          select_options: {
            sorted_by: BillsReceife.options_for_sorted_by
          },
          default_filter_params: { sorted_by: '' }
        ) or return

       
      @bills_receives = @filterrific.find.page(params[:page]) 

      if params[:filterrific].present? && !params[:filterrific][:grouped_by].blank?        
          if params[:filterrific][:grouped_by] === 'category_id'
            @grouped = @bills_receives.group_by(&:category_id)          
          elsif params[:filterrific][:grouped_by] === 'financial_account_id'
            @grouped = @bills_receives.group_by(&:financial_account_id)
          end
      else
          @grouped = @bills_receives.group_by(&:category_id)  
      end

    respond_to do |format|
      format.html { render layout: 'print' }
      format.js
    end
  end

  def birthdays
     if params[:filterrific].present?
        @filterrific_params =  params[:filterrific].permit(["reset_filterrific", 'per_date', "sorted_by", "birthdate_sorted_by"]).to_h.stringify_keys
      else
        @filterrific_params = nil
      end

    @filterrific = initialize_filterrific(
          PeopleAssociated.actives.includes(:workplace, :office),
          @filterrific_params,
          select_options: { birthdate_sorted_by: PeopleAssociated.birthdate_options_for_sorted_by },
          default_filter_params: { birthdate_sorted_by: 'birthdate_asc' }
        ) or return
        
        @birthdays = @filterrific.find if params[:filterrific] && params[:filterrific][:per_date] #.page(params[:page])
  end	

  def birthdays_print
    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["reset_filterrific", 'per_date', "sorted_by", "birthdate_sorted_by"]).to_h.stringify_keys
    else
      @filterrific_params = nil
    end


		@filterrific = initialize_filterrific(
          PeopleAssociated.actives.includes(:workplace, :office),
          @filterrific_params,          
          select_options: { birthdate_sorted_by: PeopleAssociated.birthdate_options_for_sorted_by },
          default_filter_params: { birthdate_sorted_by: 'birthdate_asc' }
        ) or return
        
      	@birthdays = @filterrific.find

        respond_to do |format|
          format.html { render layout: 'print' }
          format.js
      end
	end


  def birthdays_to_xls

    @filterrific = initialize_filterrific(
          PeopleAssociated.actives.includes(:workplace, :office),
          params[:filterrific],
          select_options: { birthdate_sorted_by: PeopleAssociated.birthdate_options_for_sorted_by },
          default_filter_params: { birthdate_sorted_by: 'birthdate_asc' }
        ) or return


      @birthdays = @filterrific.find

      to_export = []
      @birthdays.each do |people_associated|
        to_export << {
          "Data de Nascimento": people_associated.birthdate ? I18n.l(people_associated.birthdate, format: :custom_short) : '',
          "Nome": people_associated.name,
          "Logradouro": people_associated.full_address.split(",").reject { |c| c.blank? }.size > 0 ? people_associated.full_address : "",
          "Local de Trabalho": people_associated.workplace.present? ? people_associated.workplace.name : '',
          "Cargo": people_associated.office.present? ? people_associated.office.name : '',
          "Telefone": people_associated.phone,
          "Celular": people_associated.cell_phone1   
        }.compact
      end

      to_export << {"Sem Resultados": ""} if to_export.blank?

      respond_to do |format|
        format.xls { send_data(to_export.to_xls, filename: "Relatorio_Aniversariantes_#{Date.current.strftime("%d_%m_%Y")}.xls") }
      end
  end


def voters
     if params[:filterrific].present?
        @filterrific_params =  params[:filterrific].permit(["reset_filterrific", 'with_workplace_ids', "birthdate_sorted_by"]).to_h.stringify_keys
      else
        @filterrific_params = nil
      end

    @filterrific = initialize_filterrific(
          PeopleAssociated.actives.includes(:workplace, :office),
          params[:filterrific],
          select_options: { birthdate_sorted_by: PeopleAssociated.birthdate_options_for_sorted_by },
          default_filter_params: { birthdate_sorted_by: 'name_asc' }
        ) or return
        
        @birthdays = @filterrific.find  #.page(params[:page])
  end 

  def voters_print
    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["reset_filterrific", 'with_workplace_ids', "birthdate_sorted_by"]).to_h.stringify_keys
    else
      @filterrific_params = nil
    end


    @filterrific = initialize_filterrific(
          PeopleAssociated.actives.includes(:workplace, :office),
          @filterrific_params,          
          select_options: { birthdate_sorted_by: PeopleAssociated.birthdate_options_for_sorted_by },
          default_filter_params: { birthdate_sorted_by: 'name_asc' }
        ) or return
        
        @birthdays = @filterrific.find

        respond_to do |format|
          format.html { render layout: 'print' }
          format.js
      end
  end


  def voters_to_xls
    if params[:filterrific].present?
      @filterrific_params =  params[:filterrific].permit(["reset_filterrific", 'with_workplace_ids', "birthdate_sorted_by"]).to_h.stringify_keys

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_list_business.html.erb
<div id="filterrific_results">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th><%= Company.human_attribute_name(:name) %></th>              
        <th><%= Company.human_attribute_name(:segment) %></th> 
        <th><%= Company.human_attribute_name(:phone) %></th>              
        <th><%= Company.human_attribute_name(:benefit) %></th>                   
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @business) do |busines| %>
      <td><%= busines.name %></td>                                    
      <td><%= busines.segment ? busines.segment.name : "Nada informado" %></td>                            
      <td><%= busines.phone %></td>                                    
      <td><%= busines.benefit %></td>                                    

      <% end %>
    </tbody>
  </table>

  <%= will_paginate @business, renderer: BootstrapPagination::Rails %>
</div>

app/views/reports/associateds.html.erb
<%= stylesheet_link_tag "print", media: :print %> 

<div class="card no-print">
  <div class="card-header ch-alt m-b-20">   
    <i class="zmdi zmdi-filter-list"></i> Filtros
  </div>  
  
  <div class="card-body card-padding "> 
    <%= form_for_filterrific @filterrific, html: { class: "", role: "form", id: 'filterrific-no-ajax-auto-submit' } do |f| %>
      <div class="row">
          <div class="col-md-2 col-sm-2 col-xs-2">
            Data filiação inicial
            <div class="form-group fg-line">          
             <%= f.text_field :with_affiliate_date_gte, :class => "form-control mask-date", :placeholder => "Data filiação Inicial" %>
            </div>         
          </div>  

          <div class="col-md-2 col-sm-2 col-xs-2">
            Data filiação final
            <div class="form-group fg-line">
              <%= f.text_field :with_affiliate_date_lte, :class => "form-control mask-date", :placeholder => "Data filiação Final" %>
            </div>      
          </div>  

          <div class="col-md-4 col-sm-4 col-xs-4">
            <div class="form-group fg-line">
              Por sexo:
              <%= f.select(
                :with_gender_name,
                PeopleAssociated::GENDERS.collect {|g| [ g, g ] },
                { include_blank: '- Todos -' }, class: 'selectpicker'
                ) %>
            </div>                
          </div>


          <div class="col-md-4 col-sm-4 col-xs-4">
            <div class="form-group fg-line">
              Por vínculo:
              <%= f.select(
                :with_bond_ids,
                PeopleAssociated::BOND.collect {|g| [ g[0], g[1] ] },
                { include_blank: '- Todos -' }, class: 'selectpicker'
                ) %>
            </div>                
          </div>
      </div>  

      <div class='row'>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <div class="form-group fg-line">
            Por situação:
            <%= f.select(
              :with_situation_ids,
              PeopleAssociated::SITUATION.collect {|g| [ g[0], g[1] ] },
              { include_blank: '- Todos -' }, class: 'selectpicker'
              ) %>
          </div>                
        </div>  


        <div class="col-md-4 col-sm-4 col-xs-4">
          <div class="form-group fg-line">
            Por cargos:
            <%= f.select(
              :with_office_ids,
              Office.all.collect {|o| [ o.name, o.id ] },
              { include_blank: '- Todos -' }, class: 'selectpicker'
              ) %>
          </div>                
        </div>  

        <div class="col-md-4 col-sm-4 col-xs-4">
          <div class="form-group fg-line">
            Por funções:
            <%= f.select(
              :with_occupation_ids,
              Occupation.all.collect {|o| [ o.name, o.id ] },
              { include_blank: '- Todos -' }, class: 'selectpicker'
              ) %>
          </div>                
        </div>  
      </div>

      <div class='row'>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <div class="form-group fg-line">
            Por Secretarias:
            <%= f.select(
            :with_department_ids,
            Department.all.collect {|o| [ o.name, o.id ] },
            { include_blank: '- Todos -' }, class: 'selectpicker'
            ) %>
          </div>                
        </div> 

        <div class="col-md-4 col-sm-4 col-xs-4">
          <div class="form-group fg-line">
            Por local de trabalho:
            <%= f.select(
            :with_workplace_ids,
              Workplace.all.collect {|w| [ w.name, w.id ] },
              { include_blank: '- Todos -' }, class: 'selectpicker'
            ) %>
          </div>                
        </div>

        <div class="col-md-4 col-sm-4 col-xs-4">
          Ordenar por:
          <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], {}, {class: 'selectpicker'} ) %>
        </div>

        <div class="col-md-8 col-sm-2 col-xs-2">
          <div class="form-group fg-line">  
            <%= f.submit 'Filtrar', class: "btn bgm-green waves-effect" %>                
            <%= link_to('Resetar Filtros', reset_filterrific_url, class: "btn bgm-red waves-effect")%>
          </div>
        </div>
      </div>

      <%= render_filterrific_spinner %>      
    <% end %>
  </div>
</div>

<div class="card">
  <div class="action-header clearfix">
    <div class="ah-label hidden-xs">  <i class="zmdi zmdi-account-box-o"></i> <%= PeopleAssociated.model_name.human.pluralize %> </div>
    <% if @people_associateds %>
      <ul class="actions no-print">
        <li>
          <%
            @params = { } 
            @params.merge!({ filterrific: @filterrific_params }) if params[:filterrific].present?
          %>
          <%= link_to associateds_print_path(@params), target: :blank, title: "Imprimir" do %>
            <i class='zmdi zmdi-print'></i> 
          <% end %>
        </li>    


        <li>
           <%= link_to associateds_xml_path({format: :xls, filterrific: @filterrific.to_hash }), target: :blank, title: "Exportar Excel" do %>
            <i class="fa fa-file-excel-o"></i>                        
            <% end %>
        </li>                    
      </ul>
    <% end %>                  
</div>


  <div class="card-body"> 
    <div class="table-responsive">
      <% if @people_associateds %>
        <%= render( partial: 'reports/list_people_associateds', locals: { people_associateds: @people_associateds } )  %>
      <% else %>  
        <p> Sem resultados </p>
      <% end %>
    </div>                       
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    loadSelectPicker();
  });
</script>

app/views/reports/associateds_print.html.erb
<div class="card">
  <div class="action-header clearfix">
    <div class="ah-label hidden-xs">  <h1> Relatório de <%= PeopleAssociated.model_name.human.pluralize %> </h1> </div>            
</div>


  <div class="card-body"> 
    <div class="table-responsive">
      <% if @people_associateds %>
        <%= render( partial: 'reports/list_people_associateds', locals: { people_associateds: @people_associateds } )  %>
      <% else %>  
        <p> Sem resultados </p>
      <% end %>
    </div>                       
  </div>
</div>

app/views/reports/bills_pays_print.html.erb
<% @customer_configuration = CustomerConfiguration.current %>



<div class="card">
  <div class="action-header clearfix">        
    <div class="ah-label hidden-xs"><h1> <%= "" %> </h1></div>   
    
  </div>


  <div class="card-body"> 
    <div class="table-responsive">
      <% if @bills_pays %>
        <%= render( partial: 'reports/list_bills_pays_print', locals: { bills_pays: @bills_pays } )  %>
      <% else %>  
        <p> Sem resultados </p>
      <% end %>
    </div>                       
  </div>
</div>

app/views/reports/bills_receives.html.erb
<%= stylesheet_link_tag "print", media: :print %> 
<div class="card no-print">
  <div class="card-header ch-alt m-b-10">   
    <i class="zmdi zmdi-filter-list"></i> Filtros
  </div>  
  <div class="card-body card-padding"> 
    <%= form_for_filterrific @filterrific, html: { class: "", role: "form", id: 'filterrific-no-ajax-auto-submit' } do |f| %>
    <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-4">
            Data do Cadastro
            <div class="form-group fg-line">          
             <%= f.text_field :with_due_date_gte, :class => "form-control", :placeholder => "" %>
            </div>         
        </div>       

        <div class="col-md-4 col-sm-4 col-xs-4">
            Situação
            <div class="form-group fg-line">          
             <%= f.select :with_situation_flag, BillsReceife::STATES, { :include_blank => "Todas" }, {:class => "form-control"} %>
            </div>         
        </div>   

         <div class="col-md-4 col-sm-4 col-xs-4">
          Plano de Contas
          <div class="form-group fg-line">          
            <%= f.select :with_category_ids, options_for_select(credit_categories_options_array, @filterrific.with_category_ids), { :include_blank => "Todas" }, {:class => "form-control"} %>
          </div>   
        </div>   

      <div class="col-md-4 col-sm-4 col-xs-4">
        <div class="form-group fg-line">
         <label>Agrupar por:</label>
         <%= f.select(:grouped_by, BillsReceife.options_for_grouped_by, { selected: params[:filterrific].present? && params[:filterrific][:grouped_by].present? ? params[:filterrific][:grouped_by] : 'category_id'}, {class: 'selectpicker'} ) %>
       </div>
     </div>     

     <div class="col-md-4 col-sm-4 col-xs-4">
        <div class="form-group fg-line">
         <label>Ordenar por:</label>
         <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], {}, {class: 'selectpicker'} ) %>
       </div>
     </div>



     <div class="col-md-8 col-sm-2 col-xs-2">
      <div class="form-group fg-line">  
        <%= f.submit 'Visualizar', class: "btn bgm-green waves-effect" %>                
        <%= link_to('Resetar Filtros', reset_filterrific_url, class: "btn bgm-red waves-effect")%>
      </div>
    </div>
  </div>

  <%= render_filterrific_spinner %>      
  <% end %>
</div>
</div>

<div class="card">
  <div class="action-header clearfix">                                       
    <div class="ah-label hidden-xs"><i class="zmdi zmdi-money"></i> <%= "Relatório de Recebimentos" %> </div>

    <% if @bills_receives %>
    <ul class="actions no-print">
      <li>
          <%
            @params = { } 
            @params.merge!({ filterrific: @filterrific_params }) if params[:filterrific].present?
          %>

          <%= link_to bills_receives_print_path(@params), target: :blank, title: "Imprimir" do %>
            <i class='zmdi zmdi-print'></i> 
          <% end %>
      </li>   
<% if false %>
      <li>
         <%= link_to bills_receives_to_xls_path({format: :xls, filterrific: @filterrific.to_hash }), target: :blank, title: "Exportar Excel" do %>
          <i class="fa fa-file-excel-o"></i>                        
          <% end %>
      </li>                    
<% end %>
    </ul>
    <% end %>    
  </div>

  <div class="card-body"> 
    <div class="table-responsive">
      <% if @bills_receives %>
      <%= render( partial: 'reports/list_bills_receives', locals: { bills_receives: @bills_receives } )  %>
      <% else %>  
      <p> Sem resultados </p>
      <% end %>
    </div>                       
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    loadSelectPicker();        
    dateRangePicker("#filterrific_with_due_date_gte");
  });
</script>


<style type="text/css">
.daterangepicker {
  right: 810px !important;
}
.daterangepicker .drp-calendar {
  max-width: 330px;
}
</style>