config/routes.rb
Rails.application.routes.draw do
  get 'affiliate_service/appointment_book'
  patch 'atualizar-agenda/(:appointbook_peopleassoci_id)' => 'affiliate_service#update_appointbook_peopleassoci', as: :update_appointbook_peopleassoci

  resources :bills_pays, path: "contas-a-pagar"
  resources :customer_configurations, path: "configuracoes"
  resources :payment_forms, path: "formas-pagamento"
  resources :financial_accounts, path: "contas-contabeis"
  resources :bills_receives, path: "contas-a-receber"
  resources :bank_accounts, path: "bancos"
  resources :categories, path: "plano-contas"
  # resources :subcategories, path: "subcategorias"
  resources :efforts, path: 'autorizacao-empenho'
  resources :type_incorporations, path: 'tipo-de-incorporacoes'
  resources :suppliers, path: 'fornecedores'
  resources :rooms, path: 'salas'
  resources :heritage_groups, path: 'grupo-do-patrimonio'
  # resources :financials, path: 'financas'

  # resources :monthly_payments, path: 'mensalidades' do
  #   match :pay, path: 'pagar',  via: [:get, :patch]
  # end

  resources :workplaces, path: 'locais-de-trabalho'
  resources :segments, path: 'segmentos'
  resources :occupations, path: 'funcoes'
  resources :offices, path: 'cargos'
  resources :patrimonies, path: 'patrimonios'
  resources :departments, path: 'departamentos'
  resources :roles, path: 'regras-de-acesso'
  
  devise_for :users, path: 'usuarios-do-sistema'
  resources :users, path: 'usuários-do-sistema' do
    collection do
      get 'meu-perfil' => 'users#edit_profile'
      post 'meu-perfil' => 'users#update_profile'
    end
  end


  resources :professionals, path: "profissionais"  do 
    resources :appointment_books, path: "agenda" do
      get 'confirma'
      get 'compareceu'
      get 'cancela'
      get 'iniciar-atendimento'
      get 'finalizar-atendimento'
      post 'agendar-retorno'
    end
  end
  
   resources :inventories, path: "estoque" do 
    resources :inventory_movements, path: "movimento-estoque"
   end
   
   resources :companies, path: "empresas-conveniadas"
   
   resources :member_access, path: "area-associado" do 
      collection do
        get 'meu-perfil' => 'member_access#edit_profile'
        post 'meu-perfil' => 'member_access#update_profile'
      end
   end
   
   devise_for :people_associateds, path: 'acesso-associado', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'people_associateds/sessions',
     passwords: 'people_associateds/passwords',
   }   
  
   resources :member_access_dependent, path: "area-dependente" do 
      collection do
        get 'meu-perfil' => 'member_access_dependent#edit_profile'
        post 'meu-perfil' => 'member_access_dependent#update_profile'
      end
   end

   devise_for :dependents, path: 'acesso-dependente', 
   path_names: { sign_in: 'login', sign_out: 'logout', session: 'sessao', password: 'recuperar-senha' }, 
   controllers: {
     sessions: 'dependents/sessions',
     passwords: 'dependents/passwords',
   }

   resources :people_associateds, path: "associados" do
   	resources :dependents, path: "dependentes"
    collection do
      get 'autocomplete'
      get 'search'
      get 'print'
      get 'find_by_cpf'
      get 'load_all'
      get 'my_dependents'
    end  
   end
	
  get 'exportar-associados-em-xls' => 'people_associateds#people_associateds_to_xls', as: :people_associateds_to_xls
  get 'carteirinha/:id' => 'people_associateds#wallet', as: :wallet
  get 'ficha/:id' => 'people_associateds#record', as: :record
  get 'declaracao-uniao-estavel/(:id)' => 'people_associateds#stable_union_statement', as: :stable_union_statement
  get 'declaracao-associado/(:id)' => 'people_associateds#affiliate_statement', as: :affiliate_statement
  get 'desfiliacao-associado/(:id)' => 'people_associateds#affiliate_defiliation', as: :affiliate_defiliation
  get 'declaracao-comprovacao-de-dependente/(:id)' => 'people_associateds#declaration_of_dependency', as: :declaration_of_dependency
  get 'requerimento-desfiliacao/(:id)' => 'people_associateds#affiliation_requirement', as: :affiliation_requirement
  get 'desmarcar-associados-em-analise' => 'people_associateds#clear_all_in_analysis', as: :clear_all_in_analysis

  controller :reports do
    get :birthdays, path: "relatorio-aniversariantes"
    get :birthdays_print, path: "imprimir-relatorio-aniversariantes", as: :birthdays_print
    get :birthdays_to_xls, path: "exportar-relatorio-aniversariantes", as: :birthdays_to_xls
    get :associateds, path: "relatorio-associados"
    get :associateds_print, path: "relatorio-associados-impressao"
    get :associateds_xml, path: 'exportar-associados-em' 
    get :business, path: "relatorio-empresas"
    get :stocks, path: "relatorio-inventarios"
    get :heritages, path: "relatorio-patrimonios"
    get :calls, path: "relatorio-atendimentos"
    get :dependents, path: "relatorio-dependentes"
    get :print_dependents, path: "imprimir-relatorio-dependentes", as: :print_dependents
    get :monthly_payments, path: "relatorio-mensalidades", as: :monthly_payments_report
    get :voters, path: "relatorio-votantes"
    get :voters_print, path: "imprimir-relatorio-votantes", as: :voters_print
    get :voters_to_xls, path: "exportar-relatorio-votantes", as: :voters_to_xls
    get :bills_receives, path: "relatorio-contas-receber", as: :report_bills_receives
    get :bills_receives_print, path: "imprimir-relatorio-contas-receber", as: :bills_receives_print
    get :bills_receives_to_xls, path: "exportar-relatorio-contas-receber", as: :bills_receives_to_xls
    get :bills_pays, path: "relatorio-contas-pagar", as: :report_bills_pays
    get :bills_pays_print, path: "imprimir-relatorio-contas-pagar", as: :bills_pays_print
    get :bills_pays_to_xls, path: "exportar-relatorio-contas-pagar", as: :bills_pays_to_xls
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard
  
  ##### WHATSAPP
  # post 'twilio' => 'dashboard#twilio', as: :twilio
	# post 'twilio_message' => 'dashboard#twilio_message', as: :twilio_message
  ##### SMS
  # post '/twilio/sms'
  #get '/sms/confirma/:token' => 'twilio#confirma', as: :sms_confirma
  post 'comtele/sms'

  match 'site/filiacao' => 'site#inscription',  via: [:get, :post], as: :site_inscription
  match 'site/bem-vindos' => 'site#welcome',  via: [:get], as: :site_welcome
  
	root :to => "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/people_associated.rb
#encoding: utf-8
class PeopleAssociated < ApplicationRecord
  mount_base64_uploader :photo, PeopleAssociatedPhotoUploader

  acts_as_birthday :birthdate

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, #:validatable, password_length: 6..128, 
         :authentication_keys => [:login]

  validates :name, :cpf, presence: true#, :validity_card
  validates :cpf, uniqueness: true, unless: Proc.new { |p| p.cpf.blank? }
  validates :username, uniqueness: true, unless: Proc.new { |u| u.username.blank? }
  validates :number_registration, uniqueness: true
  validates :password, :confirmation => true, :length => { :within => 6..128 }, unless: lambda{ |user| user.password.blank? }  

  validate :cpf_valid?
  
  validates :email, :cell_phone1, :gender, :scholarity, :office_id, :occupation_id, :birthdate,
  :department_id, :profession, :workplace_id, :bond, presence: true, if: Proc.new { |p| !p.public_form.nil? && p.public_form }


  has_many :dependents, dependent: :destroy
  accepts_nested_attributes_for :dependents, reject_if: :all_blank, allow_destroy: true

  has_many :appointbook_peopleassoci, dependent: :destroy, inverse_of: :people_associated
  has_many :appointment_books, through: :appointbook_peopleassoci

  has_many :monthly_payments, dependent: :destroy
  has_many :bills_receifes, dependent: :destroy

  belongs_to :office
  belongs_to :occupation
  belongs_to :department
  belongs_to :workplace

  has_many :system_attachments, dependent: :destroy
  accepts_nested_attributes_for :system_attachments, reject_if: :all_blank, allow_destroy: true


  before_create :create_member_access_default
  before_create :create_token
  before_save :change_in_analysis
  
  attr_accessor :login, :public_form

    
  def cpf_valid?
     errors.add(:cpf, ("não é válido")) unless check_cpf(self.cpf)
  end


  def check_cpf(cpf=nil)
    return false if cpf.nil?

      winvalidos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000}
      wvalor = cpf.scan /[0-9]/
    if wvalor.length == 11
        unless winvalidos.member?(wvalor.join)
            wvalor = wvalor.collect{|x| x.to_i}
            wsoma = 10*wvalor[0]+9*wvalor[1]+8*wvalor[2]+7*wvalor[3]+6*wvalor[4]+5*wvalor[5]+4*wvalor[6]+3*wvalor[7]+2*wvalor[8]
            wsoma = wsoma - (11 * (wsoma/11))
            wresult1 = (wsoma == 0 or wsoma == 1) ? 0 : 11 - wsoma
            if wresult1 == wvalor[9]
              wsoma = wvalor[0]*11+wvalor[1]*10+wvalor[2]*9+wvalor[3]*8+wvalor[4]*7+wvalor[5]*6+wvalor[6]*5+wvalor[7]*4+wvalor[8]*3+wvalor[9]*2
              wsoma = wsoma - (11 * (wsoma/11))
              wresult2 = (wsoma == 0 or wsoma == 1) ? 0 : 11 - wsoma
              return true if wresult2 == wvalor[10] # CPF validado
            end
        end
    end
    return false # CPF invalidado
  end


  GENDERS = %w(Feminino Masculino Outro)
  MARITAL_STATUS = %w(Solteiro(a) Casado(a) Divorciado(a) Viúvo(a) União\ Estável)
  SCHOLARITY = [
    ["Fundamental Incompleto", 1],
    ["Fundamental Completo", 2],
    ["Ensino Médio Incompleto", 3],
    ["Ensino Médio Completo", 4],
    ["Superior Incompleto", 5],
    ["Superior Completo", 6],
    ["Pós-Graduação", 7],
    ["Mestrado", 8],
    ["Doutorado", 9]
  ]

  SITUATION = [
    ["Em Análise", 0],
    ["Ativo", 1],
    ["Inativo", 2],
    ["Licença interesse particular", 3],
    ["Licença Maternidade", 4],
  ]
  
  BOND = [
    ["Concursado", 1],
    ["Comissionado", 2],
    ["Contratado", 3],
    ["Eletivo", 4],
    ["Estagiário", 5],
    ["Aposentado", 6],
    ["Pensionista", 7]    
  ]  

  BLOOD_TYPE = [
    ["A+", 1],
    ["A-", 2],
    ["B+", 3],
    ["B-", 4],
    ["AB+", 5],
    ["AB-", 6],
    ["O+", 7],
    ["O-", 7]    
  ]

  BREED = [
    ["Branco(a)", 1],
    ["Moreno(a)", 2],
    ["Negro(a)", 3]
  ]

  scope :next_number_registration, -> { PeopleAssociated.maximum(:number_registration).to_i + 1 }
  scope :actives, -> { where(['situation = ?', 1]) }
  scope :in_analysis, -> { where(['in_analysis = ? OR situation = ?', true, 0]) }

  filterrific(
    available_filters: [
      :sorted_by,
      :birthdate_sorted_by,
      :per_date,
      :search_query,             
      :with_gender_name,
      :with_situation_ids,
      :with_bond_ids,
      :with_office_ids,
      :with_occupation_ids,
      :with_affiliate_date_gte,
      :with_affiliate_date_lte,
      :with_department_ids,
      :with_workplace_ids,
      :with_active_flag  
    ]
  )

  def self.options_for_sorted_by
    [
      ['Nome (a-z)', 'name_asc'],
      ['Nome (z-a)', 'name_desc'],
      ['Ordem de registro', 'number_registration_asc'],
      ['Ordem de matricula', 'hollering_registration_asc'],
      ['Data de cadastro (recentes primeiro)', 'created_at_desc'],
      ['Data de cadastro (antigos primeiro)', 'created_at_asc']
    ]
  end

  def self.birthdate_options_for_sorted_by
    [
      ['Nome (a-z)', 'name_asc'],
      ['Nome (z-a)', 'name_desc'],
      ['Data de aniversario (1-31)', 'birthdate_asc'],
      ['Data de aniversario (31-1)', 'birthdate_desc']
    ]
  end

  scope :with_active_flag, lambda { |flag|
    joins(:dependents).where("dependents.active = ?", [*flag])
  }  

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 1
    where(
      terms.map {
        or_clauses = [
          "LOWER(people_associateds.name) LIKE ?"               
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  # scope :search_workplace, lambda { |query|
  #   return nil  if query.blank?
  #   # condition query, parse into individual keywords
  #   terms = query.downcase.split(/\s+/)
  #   # replace "*" with "%" for wildcard searches,
  #   # append '%', remove duplicate '%'s
  #   terms = terms.map { |e|
  #     ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
  #   }
  #   # configure number of OR conditions for provision
  #   # of interpolation arguments. Adjust this if you
  #   # change the number of OR conditions.
  #   num_or_conditions = 1
  #   where(
  #     terms.map {
  #       or_clauses = [
  #         "LOWER(people_associateds.workplace) LIKE ?"         
  #       ].join(' OR ')
  #       "(#{ or_clauses })"
  #     }.join(' AND '),
  #     *terms.map { |e| [e] * num_or_conditions }.flatten
  #   )
  # }


  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("people_associateds.created_at #{ direction }")
    when /^name_/
      order("LOWER(people_associateds.name) #{ direction }")
    when /^number_registration_/
      order("people_associateds.number_registration #{ direction }")  
    when /^hollering_registration_/
      order("length(people_associateds.hollering_registration), people_associateds.hollering_registration  #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :birthdate_sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^birthdate_/
      order("MONTH(people_associateds.birthdate)#{ direction }, DAY(people_associateds.birthdate)#{ direction }")
    when /^name_/
      order("LOWER(people_associateds.name) #{ direction }")
    when /^number_registration_/
      order("LOWER(people_associateds.number_registration) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :with_affiliate_date_gte, lambda { |ref_date|
    where('DATE(affiliate_date) >= ?', ref_date.to_date)
  }

  scope :with_affiliate_date_lte, lambda { |ref_date|
    where('DATE(affiliate_date) <= ?', ref_date.to_date)
  }

  scope :with_gender_name, lambda { |gender_names|
    where(gender: [*gender_names])
  }  

  scope :with_situation_ids, lambda { |situation_ids|
    where(situation: [*situation_ids])
  }  

  scope :with_bond_ids, lambda { |bond_ids|
    where(bond: [*bond_ids])
  }

  scope :with_office_ids, lambda { |office_ids|
    where(office_id: [*office_ids])
  }

  scope :with_occupation_ids, lambda { |occupation_ids|
    where(occupation_id: [*occupation_ids])
  }  

  scope :with_department_ids, lambda { |department_ids|
    where(department_id: [*department_ids])
  }

  scope :with_workplace_ids, lambda { |workplace_ids|
    where(workplace_id: [*workplace_ids])
  }

  scope :per_date, lambda { |dates|
    #d = dates#.split('-')
    #PeopleAssociated.find_birthdates_for(Date.parse(dates))
    if dates.blank?
      PeopleAssociated.all
    else
      PeopleAssociated.where("MONTH(birthdate) = ?", dates)
    end
  }

  def self.find_by_cell_phone(phone)
    where('cell_phone1 = :phone OR cell_phone2 = :phone', phone: phone).first
  end

  def self.search(search)
    pa = where(["name LIKE ?", "%#{search}%"])    
    de = Dependent.where(["name LIKE ?", "%#{search}%"])

    return pa, de
  end

  def self.search_by_name(search)
    #joins(:dependents).where(["people_associateds.name LIKE ? OR dependents.name LIKE ?", "%#{search}%", "%#{search}%"])  
    pa = where(["name LIKE ?", "%#{search}%"]).map { |e| { name: "#{e.name} / #{e.phone}", id: e.id, type: "people_associated" } }    

app/controllers/people_associateds/confirmations_controller.rb
class PeopleAssociateds::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/people_associateds/passwords_controller.rb
class PeopleAssociateds::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/helpers/people_associateds_helper.rb
module PeopleAssociatedsHelper
end

app/views/people_associateds/_my_dependents_checkbox.html.erb
<div class="card-header">
	<br>
	<h5>MARQUE O(S) DEPENDENTE(S)</h5>
	<table class="table table-hover">
	    <thead>
	      <tr>
	      	<th>√</th>
	        <th>Nome</th>
	        <th>Grau de Parentesco</th>       
	        <th>Situação</th>       
	      </tr>
	    </thead>
	    <tbody>
			<% @dependents.order("name asc").each do |dependent| %>
				<tr>
					<td>
						<div class="checkbox m-b-15">
				  			<label>
				    			<%= check_box_tag 'dependent_ids[]', dependent.id %>
				    			<i class="input-helper"></i> 				    			
				  			</label>
						</div>  
					</td>
					<td><%= h dependent.name %></td>
					<td><%= dependent.degree_of_kinship_name %></td>
					<td><%= dependent.active ? "Ativo" : "Inativo" %></td>
				</tr>
				                        
			<% end %> 
		</tbody>
</div>

app/views/people_associateds/affiliate_statement.js.erb
var redirectWindow = window.open("<%=affiliate_statement_url(@p)%>", '_blank');
redirectWindow.location;

app/views/people_associateds/load_all.js.erb
<% js = escape_javascript(render(partial: 'shared/select_associados')) %>
$("#pa_generate_file").html("<%= js %>");	
hiddenPreLoader(); 

app/views/people_associateds/show.html.erb
<div class="container container-alt">
    <div class="block-header">
        <h2><strong><%= @people_associated.name %></strong>
            <small>Local de trabalho: <%= @people_associated.workplace.present? ? @people_associated.workplace.name : '' %></small>
        </h2>  

        
        <ul class="actions">
            <li>
                <%= link_to edit_people_associated_path(@people_associated), title: "Editar " do %>
                    <%= content_tag(:i, nil, class: "zmdi zmdi-edit") %>                    
                <% end if current_user.allowed_to?({controller: 'people_associateds', action: 'edit'}, global: true) %>            
            </li>               
        </ul>
    </div>

    <div class="card" id="profile-main">
        <div class="pm-overview <%= !@people_associated.situation.nil? && @people_associated.situation.to_i < 3 ? "pm-overview-#{@people_associated.situation}" : "" %> c-overflow">

            <div class="pmo-pic">
                <div class="p-relative">
                    <a href="<%=edit_people_associated_path(@people_associated)%>">
                        <%= image_tag @people_associated.photo.present? ? @people_associated.photo.url : 'user.png', class: "img-responsive", size: "259x194" %>
                    </a>                    

                    <% if  !@people_associated.situation.nil? %>   
                    <div class="pmo-stat <%= @people_associated.situation.to_i < 3 ? "pmo-stat-#{@people_associated.situation}" : "" %>">
                        <p class="m-0 c-white" style="font-size: 18px;">
                            <%= best_in_place @people_associated, :situation, :as => :select, :collection => PeopleAssociated::SITUATION.collect {|sit| [sit[1], sit[0]] } %></p>
                    </div>
                    <% end %>
                </div>
            </div>

            <div class="pmo-block pmo-contact hidden-xs">
                <h2>Contato</h2>

                <ul>
                    <% if @people_associated.phone.present? %>
                        <li><i class="zmdi zmdi-phone"></i><%= @people_associated.phone %></li>
                    <% end %>

                    <% if @people_associated.cell_phone1.present? %>
                        <li><i class="zmdi zmdi-phone"></i><%= @people_associated.cell_phone1 %></li>
                    <% end %>

                    <% if @people_associated.cell_phone2.present? %>
                        <li><i class="zmdi zmdi-phone"></i><%= @people_associated.cell_phone2 %></li>
                    <% end %>

                    <% if @people_associated.email.present? %>
                        <li><i class="zmdi zmdi-email"></i> <%= @people_associated.email %></li>                    
                    <% end %>
                    <li>
                        <i class="zmdi zmdi-pin"></i>
                        <address class="m-b-0 ng-binding">
                            <%= @people_associated.address %>, <%= @people_associated.number %>, <%= @people_associated.burgh %><br>
                            <%= @people_associated.zipcode %>, <%= @people_associated.city %>/<%= @people_associated.state %>
                            
                        </address>
                    </li>
                </ul>
            </div>

            <div class="pmo-block pmo-items hidden-xs">                
            </div>
        </div>

        <div class="pm-body clearfix">
            <ul class="tab-nav tn-justified">
                <li role="presentation" class="active"><a href="#about" aria-controls="about" role="tab" data-toggle="tab">Sobre</a></li>
                <li role="presentation" class=""><a href="#dependents" aria-controls="dependents" role="tab" data-toggle="tab">Dependentes</a></li>
            </ul>            

            <div class="pmb-block">
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="about">
                    <div class="pmbb-header">
                        <h2><i class="zmdi zmdi-account m-r-10"></i> Informações Básicas</h2>                    
                    </div>
                    <div class="pmbb-body p-l-30">
                        <div class="pmbb-view">
                            <dl class="dl-horizontal">
                                <dt><%= PeopleAssociated.human_attribute_name(:name) %></dt>
                                <dd><%= @people_associated.name %></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><%= PeopleAssociated.human_attribute_name(:gender) %></dt>
                                <dd><%= @people_associated.gender %></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><%= PeopleAssociated.human_attribute_name(:birthdate) %></dt>
                                <dd><%= @people_associated.birthdate ? I18n.l(@people_associated.birthdate) : "Não informado" %></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><%= PeopleAssociated.human_attribute_name(:marital_status) %></dt>
                                <dd><%= @people_associated.marital_status %></dd>
                            </dl>
                            <dl class="dl-horizontal">
                               <dt><%= PeopleAssociated.human_attribute_name(:cpf) %></dt>
                               <dd><%= @people_associated.cpf %></dd>
                           </dl>
                           <dl class="dl-horizontal">
                               <dt><%= PeopleAssociated.human_attribute_name(:rg) %></dt>
                               <dd><%= @people_associated.rg %></dd>
                           </dl>
                       </div>              
                   </div>
               </div>

               <div role="tabpanel" class="tab-pane" id="dependents">
                <div class="pmbb-header">
                    <h2><i class="zmdi zmdi-accounts m-r-10"></i> Dependentes</h2>                    
                </div>
                <div class="pmbb-body p-l-30">
                  <div class="pmbb-view">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                          <tr>
                            <th><%= Dependent.human_attribute_name(:name) %></th>
                            <th><%= Dependent.human_attribute_name(:birthdate) %></th>
                            <th><%= Dependent.human_attribute_name(:degree_of_kinship) %></th>
                            <th><%= Dependent.human_attribute_name(:active) %></th>       
                          </tr>
                        </thead>

                        <tbody>
                          <% @people_associated.dependents.order(name: :asc).each do |dependent| %>
                            <tr>
                              <td><%= dependent.name %></td>
                              <td><%= dependent.birthdate ? I18n.l(dependent.birthdate) : 'Não informado' %></td>           
                              <td><%= dependent.degree_of_kinship_name %></td>           
                              <td style="width: 200px;">
                                <span class="label label-<%= dependent.active ? 'success' : 'danger'%>">
                                    <%= best_in_place dependent, :active, url: people_associated_dependent_path(@people_associated, dependent),  as: :select, collection: [[true, 'Sim'], [false, 'Não']] %>
                                </span>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table> 
                </div>  
            </div>  
        </div>
    </div>
</div>            
</div>
</div>
</div>

app/views/people_associateds/stable_union_statement.js.erb
var redirectWindow = window.open("<%=stable_union_statement_url(@p)%>", '_blank');
redirectWindow.location;